AWSTemplateFormatVersion: '2010-09-09'
Description: Create VPC with 3 Subnets and an Internet Gateway

Parameters:
  BaseName:
    Type: String
    Description: Base name (e.g., build10) of the VPC and subnets
  VpcCidr:
    Type: String
    Description: CIDR block for the VPC
  SubnetNetmaskLength:
    Type: Number
    Description: Reversed netmask length for the subnets (e.g., 6 for /26)
    Default: 6

Resources:
  ClusterVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${BaseName}-vpc'
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - '${BaseName}-public-${AZ}'
            - AZ: !Sub '${AWS::Region}a'
      VpcId: !Ref ClusterVPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 4, !Ref SubnetNetmaskLength]]
      AvailabilityZone: !Sub '${AWS::Region}a'
      MapPublicIpOnLaunch: true

  SubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - '${BaseName}-public-${AZ}'
            - AZ: !Sub '${AWS::Region}b'
      VpcId: !Ref ClusterVPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 4, !Ref SubnetNetmaskLength]]
      AvailabilityZone: !Sub '${AWS::Region}b'
      MapPublicIpOnLaunch: true

  SubnetC:
    Type: 'AWS::EC2::Subnet'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub
            - '${BaseName}-public-${AZ}'
            - AZ: !Sub '${AWS::Region}c'
      VpcId: !Ref ClusterVPC
      CidrBlock: !Select [2, !Cidr [!Ref VpcCidr, 4, !Ref SubnetNetmaskLength]]
      AvailabilityZone: !Sub '${AWS::Region}c'
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${BaseName}-igw'

  GatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref ClusterVPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref ClusterVPC
      Tags:
        - Key: Name
          Value: !Sub '${BaseName}-rt'

  SubnetARouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref RouteTable

  SubnetBRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref RouteTable

  SubnetCRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetC
      RouteTableId: !Ref RouteTable

  DefaultRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  FlowLogRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: flowlogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:ci-${BaseName}-flowlog:*'

  FlowLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: ci-${BaseName}-flowlog
      RetentionInDays: 7

  FlowLog:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      DeliverLogsPermissionArn: !GetAtt FlowLogRole.Arn
      LogGroupName: ci-${BaseName}-flowlog
      ResourceId: !Ref ClusterVPC
      ResourceType: VPC
      TrafficType: ALL

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref ClusterVPC
  SubnetAId:
    Description: The ID of Subnet A
    Value: !Ref SubnetA
  SubnetBId:
    Description: The ID of Subnet B
    Value: !Ref SubnetB
  SubnetCId:
    Description: The ID of Subnet C
    Value: !Ref SubnetC