apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: investigator-workspace-data
  namespace: investigator
  labels:
    app: investigator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
